spring.application.name=tech-store

#Perfil activo
spring.profiles.active=dev

#Context Path
server.servlet.context-path=/Tech-Store/API

#Driver for Database : PostgreSql
spring.datasource.driver-class-name=org.postgreSql.driver