#puerto para development
server.port=8090


#Configuracion de la conexion a la Bd
spring.datasource.driver-class-name=org.postgreSql.driver
spring.datasource.url=jdbc:postgresql://localhost:5432/tech_store_db
spring.datasource.username=postgres
spring.datasource.password=1234.

#Como se levanta la Bd
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

#loggins para observar el funcionamiento del Hibernate
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
